# Understanding Pandas Series and DataFrames - Lab

# Introduction

In this lab, let's get some hands on practice working with data cleanup using Pandas.

## Objectives
You will be able to:

* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('turnstile_180901.txt')
print(len(df))
df.head()

197625

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

# Practice

## Objectives
You will be able to:
* Understand and explain what Pandas Series and DataFrames are and how they differ from dictionaries and lists
* Create Series & DataFrames from dictionaries and lists
* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

# Rename all the columns to lower case

In [6]:
#Your code here
df.columns = map(lambda x:x.lower(),df.columns)

Index(['c/a', 'unit', 'scp', 'station', 'linename', 'division', 'date', 'time',
       'desc', 'entries',
       'exits                                                               '],
      dtype='object')

# Change the Index to be the Line Names

In [12]:
#Your code here
df.set_index('linename')

# Painstakingly change the index back

In [13]:
# Your code here
df.reset_index()

,index,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits
0,0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384
5,5,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,20:00:00,REGULAR,6736562,2283425
6,6,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,00:00:00,REGULAR,6736683,2283460
7,7,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,04:00:00,REGULAR,6736696,2283461
8,8,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,08:00:00,REGULAR,6736705,2283483
9,9,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,12:00:00,REGULAR,6736746,2283524
10,10,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,16:00:00,REGULAR,6736873,2283587
11,11,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,20:00:00,REGULAR,6737067,2283631
12,12,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,00:00:00,REGULAR,6737136,2283656
13,13,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,04:00:00,REGULAR,6737146,2283658
14,14,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,08:00:00,REGULAR,6737169,2283736
15,15,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,12:00:00,REGULAR,6737301,2283965
16,16,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,16:00:00,REGULAR,6737553,2284025
17,17,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,20:00:00,REGULAR,6738257,2284091
18,18,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,00:00:00,REGULAR,6738430,2284121
19,19,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,04:00:00,REGULAR,6738442,2284126
20,20,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,08:00:00,REGULAR,6738474,2284216
21,21,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,12:00:00,REGULAR,6738621,2284402
22,22,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,16:00:00,REGULAR,6738886,2284425
23,23,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,20:00:00,REGULAR,6739630,2284478
24,24,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,00:00:00,REGULAR,6739804,2284508
25,25,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,04:00:00,REGULAR,6739812,2284512
26,26,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,08:00:00,REGULAR,6739847,2284600
27,27,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,12:00:00,REGULAR,6739986,2284838
28,28,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,16:00:00,REGULAR,6740257,2284896
29,29,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,20:00:00,REGULAR,6740888,2284941
...,...,...,...,...,...,...,...,...,...,...,...,...
197595,197595,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348
197596,197596,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348
197597,197597,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348
197598,197598,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348
197599,197599,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348
197600,197600,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348
197601,197601,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348
197602,197602,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348
197603,197603,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348
197604,197604,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348
197605,197605,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348
197606,197606,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348
197607,197607,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348
197608,197608,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348
197609,197609,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348
197610,197610,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348
197611,197611,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348
197612,197612,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348
197613,197613,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348
197614,197614,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348
197615,197615,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348
197616,197616,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348
197617,197617,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348
197618,197618,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348
197619,197619,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348
197620,197620,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348
197621,197621,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348
197622,197622,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348
197623,197623,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348
197624,197624,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348

## Create another column 'Num_Lines' that is a count of how many lines pass through a station. Then sort your dataframe by this column in descending order.

In [19]:
df.columns
#df[['linename']].count()

Index(['c/a', 'unit', 'scp', 'station', 'linename', 'division', 'date', 'time',
       'desc', 'entries',
       'exits                                                               '],
      dtype='object')

In [21]:
# Your code here
df['Num_lines'] = df.station.map(lambda x: groupby('station').count()
df.LINENAME.map(lambda x: 'N' in x)

ValueError: Wrong number of items passed 10, placement implies 1

## Write a function to clean a column name.

In [ ]:
def clean(col_name):
    cleaned = #Your code here; whatever you want to do to col_name. Hint: think back to str methods.
    return cleaned

In [ ]:
#This is a list comprehension. It applies your clean function to every item in the list.
#We then reassign that to df.columns
#You shouldn't have to change anything here.
#Your function above should work appropriately here.
df.columns = [clean(col) for col in df.columns]

In [ ]:
#Checking the output, we can see the results.
df.columns

## Compare subway traffic by day of the week. Display this as a graph.

In [ ]:
#Your code here

## Is there more subway traffic on a weekend or a weekday?    Be specific in comparing magnitudes.

In [ ]:
#Your code here

# Drop a couple of columns

In [ ]:
# Your code here